config/routes.rb
Rails.application.routes.draw do
  get 'conversations/create'
  get 'conversations/show'
  devise_for :users, controllers: { registrations: 'users/registrations' ,sessions: 'users/sessions' }
  root 'static_pages#home'
  get 'static_pages/home'
  get '/conversations/:id',       to: 'conversations#show', as: :conversation
  post '/conversations/:id',      to: 'conversations#create'
  post 'conversations/:id',       to: 'messages#create'
  get '/users/:id',               to: 'users#show', as: :user
  get '/users',                   to: 'users#index'
  get '/search',                   to: 'users#search'
  get '/friends',                 to: 'users#friends'
  get '/friend_requests',         to: 'users#friend_requests'
  post 'users/:id',               to: 'friendships#create'
  patch 'users/:id',              to: 'friendships#update'
  resources :friendships
  resources :posts, only: [:create, :destroy]
  resources :messages, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :posts, dependent: :destroy
  has_many :messages

  def friends
    users_friendships = Friendship.where("(user_id = #{self.id} OR friend_id = #{self.id}) AND confirmed = true")
    friends_list =  User.all.where(id: (users_friendships.pluck :user_id)).or(User.all.where(id: (users_friendships.pluck :friend_id))).where.not(id: (self.id))
  end

  # Users who have yet to confirm friend requests
  def pending_friends
    users_friendships = friendships.where("confirmed is null or confirmed = false")
    User.all.where(id: (users_friendships.pluck :user_id)).or(User.all.where(id: (users_friendships.pluck :friend_id))).where.not(id: (self.id))
  end

  # Users who have requested to be friends
  def friend_requests
    users_friendships = inverse_friendships.where("confirmed is null")
    User.all.where(id: (users_friendships.pluck :user_id)).or(User.all.where(id: (users_friendships.pluck :friend_id))).where.not(id: (self.id))
  end

  # All users with pending requests bothe incoming and outgoing
  def all_pending_requests
    users_friendships = Friendship.where("(user_id = #{self.id} OR friend_id = #{self.id}) AND (confirmed is null)")
    User.all.where(id: (users_friendships.pluck :user_id)).or(User.all.where(id: (users_friendships.pluck :friend_id))).where.not(id: (self.id))
  end

  def confirm_friend(user)
    friendship = inverse_friendships.find{|friendship| friendship.user == user}
    friendship.confirmed = true
    friendship.save
  end

  def unfriend(unfriended_user)
    all_friendships = friendships.map {|friendship| friendship if friendship.confirmed}.compact
    all_friendships += inverse_friendships.map{ |friendship| friendship if friendship.confirmed }.compact
    deleted_friendship = all_friendships.map{ |friendship| friendship if friendship.friend == unfriended_user || friendship.user == unfriended_user}
    deleted_friendship[0].delete
  end

  def cancel_request(unfriended_user)
    pending = friendships.map{ |friendship| friendship unless friendship.confirmed }.compact
    pending = pending.map{ |friendship| friendship if friendship.friend == unfriended_user }
    pending.first.delete
  end

  def reject_request(unfriended_user)
    pending = inverse_friendships.map{ |friendship| friendship unless friendship.confirmed }.compact
    pending = pending.map{ |friendship| friendship if friendship.user == unfriended_user }
    pending.first.confirmed = false
    pending.first.save
  end

  def friend?(user)
    friends.include?(user)
  end

  def can_send_request?(user)
    if user != self && !friend?(user) && !all_pending_requests.include?(user)
      return true
    elsif rejected?(user)
      return true
    else
      return false
    end
  end

  def has_pending_request?(user)
    friend_requests.include?(user) && !rejected?(user)
  end

  def rejected?(user)
    pending_friendship = inverse_friendships.map { |friendship| friendship if friendship.user == user}.compact.first
    if pending_friendship.nil?
      return false
    elsif pending_friendship.confirmed == true || pending_friendship.confirmed.nil?
      return false
    elsif pending_friendship.confirmed == false
      return true
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_login
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  skip_before_action :require_login
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @pagy, @users = pagy(User.all) if User.all.count != 0
  end

  def search
    @pagy, @users = pagy(User.where('lower(username) like ?', "%#{params[:search_term].downcase}%").or(User.where('lower(email) like ?', "%#{params[:search_term].downcase}%")))
    flash.now[:primary] = "Showing results for \"#{params[:search_term]}\""
  end

  def show
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts) if @user.posts.count != 0
  end

  def friends
    @pagy, @users = pagy(current_user.friends)
  end

  def friend_requests
    @pagy, @users = pagy(current_user.friend_requests)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size = "")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/_user_search.html.erb
<%= form_tag("/search", :method => "get") do %>  
  <div class="input-group ml-3">  
    <%= search_field_tag :search_term, params[:search], placeholder: "Username or email", class: "form-control" %>  
    <div class="input-group-append">  
      <%= button_tag "Search for friends", class: 'btn btn-secondary', name: nil%>  
    </div>  
  </div>  
<% end %>

app/views/users/_users_list.html.erb
<div class="list-group">
    <% @users.each do |user| %>
      <div class="list-group-item">
        <div class="d-flex flex-row">
          <a href="/users/<%= user.id %>" class="mr-2"><%= gravatar_for user %></a>
          <div class="d-flex flex-column flex-grow-1">
            <div class="d-flex flex-row align-items-center justify-content-between">
              <%= link_to user.username, user, class: "m-0, username-style"%>
              <%= link_to "See Profile", user, class: "btn btn-xs btn-dark"%>
            </div>
            <% if current_user.friend?(user) %>
              <div class="text-muted text-small">
                <%= user.email %>
              </div>
            <% end %>
          </div>
        </div>
          <div class="d-flex flex-row align-items-center mt-1 justify-content-between">
            <div>
              <% if current_user.can_send_request?(user) %>
                <%= link_to 'Send Friend Request', user_path(user, params: { friendship_action: 'invite', user_id: user.id }),
                method: :post, class: "btn btn-primary btn-xs mr-1" %>
              <% elsif current_user.has_pending_request?(user) %>
                <%= link_to 'Accept Friend Request', user_path(user, params: { friendship_action: 'accept', user_id: user.id }),
                method: :update, class: "btn btn-success btn-xs mr-1" %>
                <%= link_to 'Reject Friend Request', user_path(user, params: { friendship_action: 'reject', user_id: user.id }),
                method: :update, class: "btn btn-dark btn-xs mr-1" %>
              <% elsif user != current_user && current_user.friend?(user)%>
                <%= link_to 'Unfriend', user_path(user, params: { friendship_action: 'unfriend', user_id: user.id }),
                method: :update, class: "btn btn-danger btn-xs mr-1" %>
              <% elsif current_user.pending_friends.include?(user) %>
                <%= link_to 'Cancel Friend Request', user_path(user, params: { friendship_action: 'cancel-request', user_id: user.id }),
                method: :update, class: "btn btn-danger btn-xs mr-1" %>
              <% end %>
            </div>
            <div>
              <% if current_user.friend?(user) %>
                <%= link_to 'Private Message', conversation_path(user, params: { user_id: user.id }),
                  method: :post, class: "btn btn-primary btn-xs" %>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>

app/views/users/friend_requests.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-1 col-lg-2"></div>
<div class="col-sm-12 col-md-10 col-lg-8">
  <h2>All Users</h2>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
  <%= render 'users_list'%>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
</div>
</div>
</div>

app/views/users/friends.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-1 col-lg-2"></div>
<div class="col-sm-12 col-md-10 col-lg-8">
  <h2>All Users</h2>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
  <%= render 'users_list'%>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-3 col-lg-4"></div>
<div class="col-sm-12 col-md-9 col-lg-8">
  <h2>All Users</h2>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
  <div class="list-group">
    <% @users.each do |user| %>
      <div class="list-group-item">
        <div class="d-flex flex-row">
          <a href="/users/<%= user.id %>" class="mr-2"><%= gravatar_for user %></a>
          <div class="d-flex flex-column flex-grow-1">
            <div class="d-flex flex-row align-items-center justify-content-between">
              <%= link_to user.username, user, class: "m-0, username-style"%>
              <%= link_to "See Profile", user, class: "btn btn-xs btn-dark"%>
            </div>
          </div>
        </div>
          <div class="d-flex flex-row align-items-center mt-1">
            <% if current_user.can_send_request?(user) %>
              <%= link_to 'Send Friend Request', user_path(user, params: { friendship_action: 'invite', user_id: user.id }),
              method: :post, class: "btn btn-primary btn-xs mr-1" %>
            <% elsif current_user.has_pending_request?(user) %>
              <%= link_to 'Accept Friend Request', user_path(user, params: { friendship_action: 'accept', user_id: user.id }),
              method: :update, class: "btn btn-success btn-xs mr-1" %>
              <%= link_to 'Reject Friend Request', user_path(user, params: { friendship_action: 'reject', user_id: user.id }),
              method: :update, class: "btn btn-dark btn-xs mr-1" %>
            <% elsif user != current_user && current_user.friend?(user)%>
              <%= link_to 'Unfriend', user_path(user, params: { friendship_action: 'unfriend', user_id: user.id }),
              method: :update, class: "btn btn-danger btn-xs mr-1" %>
            <% elsif current_user.pending_friends.include?(user) %>
              <%= link_to 'Cancel Friend Request', user_path(user, params: { friendship_action: 'cancel-request', user_id: user.id }),
              method: :update, class: "btn btn-danger btn-xs mr-1" %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
</div>
</div>
</div>

app/views/users/search.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-1 col-lg-2"></div>
<div class="col-sm-12 col-md-10 col-lg-8">
  <h2>Users</h2>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
    <%= render 'users_list'%>
  <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-3 col-lg-4">
  <div class="sticky-top">
    <h2><%= @user.username %></h2>
    <div><%= gravatar_for(@user, 120) %></div>
  </div>
</div>
<div class="col-sm-12 col-md-9 col-lg-8">
  <% if current_user.friend?(@user) || current_user == @user %>
    <h2>All of <%= @user.username %>'s posts</h2>
    <% if @pagy.nil?%>
      <div class="alert alert-dark" role="alert">
        <%= @user.username %> hasn't published any posts yet.
      </div>
    <% else %>
      <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
        <%= render 'posts/post_display'%>
      <div class="d-flex flex-row justify-content-center"><%== pagy_bootstrap_nav(@pagy)%></div>
    <% end %>
  <% else %>
    <div class="alert alert-dark" role="alert">
      You have to be <%= @user.username %>'s friend to see his/her posts.
    </div>
  <%end%>
</div>
</div>
</div>