config/routes.rb
Rails.application.routes.draw do
  get 'conversations/create'
  get 'conversations/show'
  devise_for :users, controllers: { registrations: 'users/registrations' ,sessions: 'users/sessions' }
  root 'static_pages#home'
  get 'static_pages/home'
  get '/conversations/:id',       to: 'conversations#show', as: :conversation
  post '/conversations/:id',      to: 'conversations#create'
  post 'conversations/:id',       to: 'messages#create'
  get '/users/:id',               to: 'users#show', as: :user
  get '/users',                   to: 'users#index'
  get '/search',                   to: 'users#search'
  get '/friends',                 to: 'users#friends'
  get '/friend_requests',         to: 'users#friend_requests'
  post 'users/:id',               to: 'friendships#create'
  patch 'users/:id',              to: 'friendships#update'
  resources :friendships
  resources :posts, only: [:create, :destroy]
  resources :messages, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alertnotice.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand navbar-expand-sm navbar-dark bg-dark fixed-top">
  <div class="d-flex flex-row w-100">
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag("rollodex-white.svg", height: "30px", width: "auto", class: "white-logo") %>
    </a>
    <%= render 'users/user_search' %>
    <div class="ml-auto" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Users", users_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "#{current_user.username}'s Profile", current_user, class: "dropdown-item" %>
          <%= link_to "#{current_user.username}'s Friends", friends_path, class: "dropdown-item" %>
          <%= link_to "Friend requests (#{current_user.friend_requests.count})", friend_requests_path, class: "dropdown-item" %>
          <%= link_to "Settings", edit_registration_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item")%> 
        </div>
        <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_session_path(:user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_registration_path(:user), class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rollodex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="<%=image_url('rollOdex.png')%>">
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/flash'%>
    <%= yield %>
    <%# debug(params) if Rails.env.development? %>
  </body>
</html>